#!/usr/bin/env python3
import os
import subprocess

if __name__ == '__main__':
    output = subprocess.run(['git', 'rev-parse', '--show-toplevel'], capture_output=True)
    base_dir = output.stdout.decode('utf-8').strip()
    output = subprocess.run(['git', 'status', '--porcelain'], capture_output=True)
    all_files = output.stdout.decode('utf-8')
    modified_files = []
    for line in all_files.split('\n'):
      if 'A' in line[0:2] or 'M' in line[0:2]:
        modified_files.append(os.path.join(base_dir, line[2:].strip()))

    for filename in modified_files:
        autopep8_call = ['autopep8', '--in-place', filename]
        subprocess.call(autopep8_call)
        subprocess.call(['git', 'add', filename])
